version: '3.3'
networks:
  net-mhpasswordmanager-mode-development:
    driver: bridge
services:
  config-services:
    image: app-nx.marcoshssilva.com.br/marcoshssilvadev/passwordmanager-configservices:latest
    restart: on-failure
    env_file:
      - envs/config-services.env
    networks:
      - net-mhpasswordmanager-mode-development
    ports:
      - "8888:8888"